### ISSUE TITLE
cannot load such file -- plist (LoadError)

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/install#38]
```
Traceback (most recent call last):
	7: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `<main>'
	6: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
	5: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:15:in `<top (required)>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- plist (LoadError)
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

**Comment by nickjhathaway** [comment]
Running into a similar issue on Ubuntu 14.04.5 LTS

Running 
```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

Results in 
```bash
==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/hathawan/.cache/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
HEAD is now at 1699a7ec1 cmd/vendor-install: Use HOMEBREW_BOTTLE_DOMAIN (#847)
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- plist (LoadError)
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:15:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `require_relative'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:15:in `<main>'
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

Any advice would be greatly appreciated, thanks!

**Comment by sjackman** [comment]
Try…
```sh
eval "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install-ruby`"
export HOMEBREW_FORCE_VENDOR_RUBY=1 
ruby -e "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install`"
```
Please let me know if that helps.

**Comment by nickjhathaway** [comment]
That did the trick, thanks!

**Comment by sjackman** [comment]
To help me troubleshoot what's going on here, do these files exist?
```
~/.linuxbrew/Homebrew/Library/Homebrew/vendor/plist/plist.rb
~/.linuxbrew/Homebrew/Library/Homebrew/vendor/plist/plist/generator.rb
~/.linuxbrew/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb
~/.linuxbrew/Homebrew/Library/Homebrew/vendor/plist/plist/version.rb
```

**Comment by sjackman** [comment]
After PR https://github.com/Linuxbrew/install/pull/39 is merged, you can run…
```sh
HOMEBREW_FORCE_VENDOR_RUBY=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by nickjhathaway** [comment]
So the linuxbrew install is in /home/linuxbrew so I checked for those files in /home/linuxbrew/.linuxbrew but they didn't exist, the whole folder ~/.linuxbrew/Homebrew/Library/Homebrew/vendor/plist/ doesn't exist 

The folder /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/ contains the following
```bash
bundle-standalone  Gemfile  Gemfile.lock  portable-ruby  portable-ruby-version  README.md
```
Doing a find on vendor for plist finds it in 
```bash
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/plist-3.4.0/lib/plist
```

let me know if any other info helps

**Comment by sjackman** [comment]
This looks like a bug in `Linuxbrew/brew` to me.

**Comment by sjackman** [comment]
This issue is resolved by PR https://github.com/Linuxbrew/brew/pull/850, which will be included in the release of Linuxbrew/brew 1.7.6. In the mean time, to fix an existing installation of Linuxbrew, run…
```sh
brew vendor-install ruby
```
or to install Linuxbrew from scratch, run…
```sh
HOMEBREW_FORCE_VENDOR_RUBY=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

**Comment by HarrisonKeeling** [comment]
> This issue is resolved by PR [Linuxbrew/brew#850](https://github.com/Linuxbrew/brew/pull/850), which will be included in the release of Linuxbrew/brew 1.7.6. In the mean time, to fix an existing installation of Linuxbrew, run…
> 
> ```shell
> brew vendor-install ruby
> ```
> 
> or to install Linuxbrew from scratch, run…
> 
> ```shell
> HOMEBREW_FORCE_VENDOR_RUBY=1 sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
> ```

```https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.armv6_linux.bottle.tar.gz``` doesn't seem to exist anymore, causing the install to fail.

**Comment by sjackman** [comment]
See this issue: https://github.com/Linuxbrew/brew/issues/781
That bottle does exist here: 
https://homebrew.bintray.com/bottles-portable-ruby/:portable-ruby-2.3.3_2.armv6_linux.bottle.tar.gz
Try…
```sh
HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com brew vendor-install ruby
```

**Comment by sjackman** [comment]
This repository is deprecated. It has been merged into Homebrew/install.
