### ISSUE TITLE
tensorflow cannot find libstd++

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/install#61]
Dear All,
My system: Redhat 7.6/64, the latest Linuxbrew version installed into default location (/home/linuxbrew). I installed Python3, then numpy, ..., torch, tensorflow using pip3. Installation was (almost) smooth. The problem happens when I try to import tensorflow:

```
Python 3.7.3 (default, Mar 30 2019, 15:09:56)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

It turns out when I compile Python3 from sources myself on the same OS, the problem does not show up. Something with path resolution?

**Comment by iMichka** [comment]
Please submit this issue at: https://github.com/Homebrew/linuxbrew-core
